name: 'Run Wopee.bot'
description: 'Run tests by Wopee Bot using docker container'

inputs:
  image:
    description: 'Full path to Wopee image'
    default: 'ghcr.io/autonomous-testing/wopee.bot:dev'
    required: false

  container_name:
    description: 'Name for container within running wopee. It will be stopped first if it is already running.'
    default: 'wopee-runner'
    required: false

  env_file:
    description: 'Path to .env file relative to current working directory'
    default: ''
    required: false

  working_directory:
    description: 'Path to working directory relative to current working directory'
    default: 'wopee-runner'
    required: false

runs:
  using: "composite"
  steps:
        
    - name: Run Wopee.bot using docker
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
        CONTAINER_NAME: ${{ inputs.container_name }}
        ENV_FILE: ${{ inputs.env_file  }}
        WORKING_DIRECTORY: ${{ inputs.working_directory }}
        SECCOMP_PROFILE: ${{ github.action_path }}/seccomp_profile.json
      run: |
        bash ${{ github.action_path }}/wopee.bot.sh \
          